- id: isort
  name: isort
  entry: pipenv run isort
  language: python
  files: \.py$
  args: ["-w", "120", "-m", "3", "-tc"]
- id: black
  name: black
  entry: pipenv run black
  language: python
  files: \.py$
  args: ["-l", "120"]
